#!/usr/bin/env node
/**
 * Sitemap generator for folkup.app.
 *
 * LAND-008 (B4) — runs after `vite-ssg build` and emits `dist/sitemap.xml`
 * with xhtml:link hreflang annotations per the Google multilingual sitemap
 * spec (https://developers.google.com/search/docs/specialty/international/localized-versions).
 *
 * SCOPE: walks dist/, includes only files generated by the vite-ssg pipeline
 * (the same allow-list as validate-build.mjs). Legacy public/ static HTML
 * (declaration, reviews, folkup-family) is OUT OF SCOPE — those have their
 * own SEO maintained alongside the content and a separate sitemap segment
 * would belong there if/when they're brought under the unified pipeline.
 *
 * lastmod strategy: best-effort `git log -1 --format=%cI <file>` per
 * prerendered HTML; falls back to today's date if the file isn't tracked by
 * git (e.g. fresh prerender output not yet committed).
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { execSync } from 'node:child_process'

const DIST = 'dist'
const HOST = 'https://folkup.app'
const LANGS = ['en', 'ru', 'pt']

/**
 * URL spec for each prerendered page in the sitemap. Mirrors the route table
 * in src/main.ts. Each entry generates a single <url> block with three
 * xhtml:link alternates + x-default.
 *
 * `sourceFor(lang)` returns the dist-relative HTML file used to derive
 * lastmod via git. The first lang's source is also used to compute <lastmod>
 * (canonical lastmod = EN page commit timestamp; alternates inherit).
 */
const PAGE_GROUPS = [
  {
    name: 'home',
    urlFor: (lang) => (lang === 'en' ? `${HOST}/` : `${HOST}/${lang}`),
    sourceFor: (lang) => (lang === 'en' ? 'index.html' : `${lang}.html`),
  },
  {
    name: 'privacy',
    urlFor: (lang) => `${HOST}/${lang}/privacy`,
    sourceFor: (lang) => `${lang}/privacy.html`,
  },
  {
    name: 'terms',
    urlFor: (lang) => `${HOST}/${lang}/terms`,
    sourceFor: (lang) => `${lang}/terms.html`,
  },
  {
    name: 'cookies',
    urlFor: (lang) => `${HOST}/${lang}/cookies`,
    sourceFor: (lang) => `${lang}/cookies.html`,
  },
]

const todayIso = new Date().toISOString().split('T')[0]

/**
 * Try to get the most recent commit date for the file backing the EN
 * variant. Falls back to today's date. Date format = YYYY-MM-DD (Google
 * accepts both full ISO 8601 and date-only).
 *
 * NOTE: the dist/ HTML file itself is gitignored, so we walk back to the
 * source content. For now use today's date — proper git-driven lastmod is
 * deferred (see TODO in commit message). This keeps the sitemap valid and
 * avoids leaking phantom freshness.
 */
function lastmodFor(_relPath) {
  return todayIso
}

const entries = []
for (const group of PAGE_GROUPS) {
  const enSource = join(DIST, group.sourceFor('en'))
  if (!existsSync(enSource)) {
    console.warn(`! skipping ${group.name}: ${enSource} not found in dist/`)
    continue
  }
  const enUrl = group.urlFor('en')
  const lastmod = lastmodFor(group.sourceFor('en'))

  const alternates = LANGS
    .filter((l) => existsSync(join(DIST, group.sourceFor(l))))
    .map((l) => `    <xhtml:link rel="alternate" hreflang="${l}" href="${group.urlFor(l)}"/>`)
  alternates.push(`    <xhtml:link rel="alternate" hreflang="x-default" href="${enUrl}"/>`)

  entries.push(`  <url>
    <loc>${enUrl}</loc>
    <lastmod>${lastmod}</lastmod>
${alternates.join('\n')}
  </url>`)
}

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${entries.join('\n')}
</urlset>
`

writeFileSync(join(DIST, 'sitemap.xml'), sitemap, 'utf8')
console.log(`✓ sitemap.xml: ${entries.length} URL groups (${entries.length * LANGS.length} alternates) → dist/sitemap.xml`)

// Silence unused-import warnings — these stay imported so they're available
// for the next-step lastmod-from-git enhancement without re-touching the file.
void readFileSync
void execSync
