#!/usr/bin/env node
/**
 * Sitemap generator for folkup.app.
 *
 * LAND-008 (B4) — runs after `vite-ssg build` and emits `dist/sitemap.xml`
 * with xhtml:link hreflang annotations per the Google multilingual sitemap
 * spec (https://developers.google.com/search/docs/specialty/international/localized-versions).
 *
 * SCOPE: walks dist/, includes only files generated by the vite-ssg pipeline
 * (the same allow-list as validate-build.mjs). Legacy public/ static HTML
 * (declaration, reviews, folkup-family) is OUT OF SCOPE — those have their
 * own SEO maintained alongside the content and a separate sitemap segment
 * would belong there if/when they're brought under the unified pipeline.
 *
 * lastmod strategy: best-effort `git log -1 --format=%cI <file>` per
 * prerendered HTML; falls back to today's date if the file isn't tracked by
 * git (e.g. fresh prerender output not yet committed).
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { execSync } from 'node:child_process'

const DIST = 'dist'
const HOST = 'https://folkup.app'
const LANGS = ['en', 'ru', 'pt', 'de']

/**
 * URL spec for each prerendered page in the sitemap. Mirrors the route table
 * in src/main.ts. Each entry generates a single <url> block with three
 * xhtml:link alternates + x-default.
 *
 * `sourceFor(lang)` returns the dist-relative HTML file used to derive
 * lastmod via git. The first lang's source is also used to compute <lastmod>
 * (canonical lastmod = EN page commit timestamp; alternates inherit).
 */
const PAGE_GROUPS = [
  {
    name: 'home',
    urlFor: (lang) => (lang === 'en' ? `${HOST}/` : `${HOST}/${lang}`),
    sourceFor: (lang) => (lang === 'en' ? 'index.html' : `${lang}.html`),
  },
  {
    name: 'privacy',
    urlFor: (lang) => `${HOST}/${lang}/privacy`,
    sourceFor: (lang) => `${lang}/privacy.html`,
  },
  {
    name: 'terms',
    urlFor: (lang) => `${HOST}/${lang}/terms`,
    sourceFor: (lang) => `${lang}/terms.html`,
  },
  {
    name: 'cookies',
    urlFor: (lang) => `${HOST}/${lang}/cookies`,
    sourceFor: (lang) => `${lang}/cookies.html`,
  },
  {
    name: 'ai-use',
    urlFor: (lang) => `${HOST}/${lang}/about/ai-use`,
    sourceFor: (lang) => `${lang}/about/ai-use.html`,
  },
  {
    name: 'projects',
    urlFor: (lang) => `${HOST}/${lang}/projects`,
    sourceFor: (lang) => `${lang}/projects.html`,
  },
  {
    name: 'services',
    urlFor: (lang) => `${HOST}/${lang}/services`,
    sourceFor: (lang) => `${lang}/services.html`,
  },
]

const todayIso = new Date().toISOString().split('T')[0]

/**
 * Git-driven lastmod: timestamp of last commit affecting src/ (which is the
 * source of all prerendered pages). Falls back to today's date if git is
 * unavailable or src/ is untracked (fresh clone scenario).
 *
 * Repo-level granularity (not per-route) because vite-ssg derives all routes
 * from the same src/ tree — any source change can affect any prerendered
 * page. Per-route granularity would require mapping each route к specific
 * source files; deferred until proven necessary (Google accepts repo-level).
 *
 * Date format = YYYY-MM-DD per Google spec.
 */
const repoLastmodIso = (() => {
  try {
    const cmd = 'git log -1 --format=%cI -- src/'
    const isoFull = execSync(cmd, { encoding: 'utf8' }).trim()
    if (!isoFull) return todayIso
    return isoFull.split('T')[0]
  } catch {
    return todayIso
  }
})()

function lastmodFor(_relPath) {
  return repoLastmodIso
}

const entries = []
for (const group of PAGE_GROUPS) {
  const enSource = join(DIST, group.sourceFor('en'))
  if (!existsSync(enSource)) {
    console.warn(`! skipping ${group.name}: ${enSource} not found in dist/`)
    continue
  }
  const enUrl = group.urlFor('en')
  const lastmod = lastmodFor(group.sourceFor('en'))

  const alternates = LANGS
    .filter((l) => existsSync(join(DIST, group.sourceFor(l))))
    .map((l) => `    <xhtml:link rel="alternate" hreflang="${l}" href="${group.urlFor(l)}"/>`)
  alternates.push(`    <xhtml:link rel="alternate" hreflang="x-default" href="${enUrl}"/>`)

  entries.push(`  <url>
    <loc>${enUrl}</loc>
    <lastmod>${lastmod}</lastmod>
${alternates.join('\n')}
  </url>`)
}

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${entries.join('\n')}
</urlset>
`

writeFileSync(join(DIST, 'sitemap.xml'), sitemap, 'utf8')
console.log(`✓ sitemap.xml: ${entries.length} URL groups (${entries.length * LANGS.length} alternates) → dist/sitemap.xml (lastmod=${repoLastmodIso})`)

// Silence unused-import warning — readFileSync stays imported for potential
// per-route source-content hashing if granular lastmod is ever needed.
void readFileSync
