#!/usr/bin/env node
/**
 * Post-build SEO infrastructure validator for folkup.app.
 *
 * LAND-008 (B3) — runs after `vite-ssg build` to enforce the gates required
 * by Phase 2 closure:
 *   1. <html lang="…"> present
 *   2. <link rel="canonical"> present
 *   3. hreflang completeness (en + ru + pt + x-default) on prerendered pages
 *   4. All JSON-LD blocks are parseable
 *   5. No rogue inline <script> outside of vite-ssg hydration markers and JSON-LD
 *
 * Exits 1 if any gate fails. Output is human-readable but machine-grep-able
 * (`✗ <path>: <reason>`).
 *
 * SCOPE: validates only files generated by the vite-ssg pipeline (the routes
 * declared in src/main.ts → includedRoutes). Legacy static HTML under
 * `public/declaration/**`, `public/reviews/**`, `public/folkup-family.html`,
 * `public/index.html`, etc. is copied verbatim and is OUT OF SCOPE — those
 * pages have their own (separately maintained) SEO and would fail the strict
 * hreflang gate if validated here.
 */

import { readFileSync, readdirSync, statSync } from 'node:fs'
import { join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const DIST = 'dist'
const LANGS = ['en', 'ru', 'pt']

/**
 * The exact set of relative paths (POSIX-style) produced by vite-ssg
 * for the routes in `includedRoutes`. Anything else under dist/ is treated
 * as legacy static and skipped.
 *
 * Mapping is derived from vite-ssg's defaults:
 *   '/'             → index.html
 *   '/ru'           → ru.html
 *   '/pt'           → pt.html
 *   '/en/privacy'   → en/privacy.html      (en/terms.html, en/cookies.html)
 *   '/ru/privacy'   → ru/privacy.html      ...
 *   '/pt/privacy'   → pt/privacy.html      ...
 *   '/404'          → 404.html
 *
 * Note: 404.html is rendered by Vue Router but is LOCALE-NEUTRAL by design —
 * it deliberately omits hreflang because nginx try_files serves dist/404.html
 * for any unmatched URL across all languages (per folkup-infra nginx config).
 * The validator honours that exception. (The «Cloudflare Pages» phrasing in
 * earlier comments was a phantom — folkup.app has been VPS nginx since
 * inception, confirmed by Кочегар DevOps verdict 2026-05-30.)
 */
const SSG_HTML_FILES = new Set([
  'index.html',
  'ru.html',
  'pt.html',
  'en/privacy.html',
  'en/terms.html',
  'en/cookies.html',
  'ru/privacy.html',
  'ru/terms.html',
  'ru/cookies.html',
  'pt/privacy.html',
  'pt/terms.html',
  'pt/cookies.html',
  '404.html',
])

/** Pages where hreflang completeness is NOT required. */
const HREFLANG_EXEMPT = new Set(['404.html'])

const errors = []
const warnings = []

function walkHtml(dir, files = []) {
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) walkHtml(path, files)
    else if (entry.endsWith('.html')) files.push(path)
  }
  return files
}

function toPosix(p) {
  return p.split(sep).join('/')
}

const htmlFiles = walkHtml(DIST)
const ssgFiles = htmlFiles.filter((f) => SSG_HTML_FILES.has(toPosix(relative(DIST, f))))
const legacyCount = htmlFiles.length - ssgFiles.length

console.log(
  `Validating ${ssgFiles.length} vite-ssg HTML files (skipping ${legacyCount} legacy static files)...`,
)

// Surface which SSG files are missing from dist — this is a hard error since
// it means the prerender step silently dropped a route.
const presentRel = new Set(ssgFiles.map((f) => toPosix(relative(DIST, f))))
for (const expected of SSG_HTML_FILES) {
  if (!presentRel.has(expected)) errors.push(`missing prerendered page: dist/${expected}`)
}

for (const file of ssgFiles) {
  const html = readFileSync(file, 'utf8')
  const rel = toPosix(relative(DIST, file))

  // Gate 1: <html lang> present + non-empty
  const langMatch = html.match(/<html\s+[^>]*lang="([^"]+)"/i)
  if (!langMatch) errors.push(`${rel}: missing <html lang="…"> attribute`)

  // Gate 2: canonical link present
  const canonMatch = html.match(/<link\s+rel="canonical"\s+href="([^"]+)"/i)
  if (!canonMatch) errors.push(`${rel}: missing <link rel="canonical">`)

  // Gate 3: hreflang completeness (en + ru + pt + x-default) on prerendered pages,
  // except for routes explicitly exempt (404).
  if (!HREFLANG_EXEMPT.has(rel)) {
    const hreflangs = [...html.matchAll(/<link\s+rel="alternate"\s+hreflang="([^"]+)"/gi)]
    const langs = hreflangs.map((m) => m[1])
    for (const expected of [...LANGS, 'x-default']) {
      if (!langs.includes(expected)) {
        errors.push(`${rel}: missing hreflang="${expected}"`)
      }
    }
  }

  // Gate 4: JSON-LD parseability
  const jsonldBlocks = [
    ...html.matchAll(/<script\s+type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/gi),
  ]
  for (const [, body] of jsonldBlocks) {
    try {
      JSON.parse(body)
    } catch (e) {
      errors.push(`${rel}: invalid JSON-LD: ${e.message}`)
    }
  }

  // Gate 5: no rogue inline <script> (must be either external src= or JSON-LD).
  // Vite/vite-ssg hydration markers and stylesheet preload triggers are NOT
  // inline scripts so they don't show up here. If they ever do (e.g. a future
  // SSR runtime adds a hydration <script>), this gate downgrades to a warning
  // for safety — we surface but don't fail until verified malicious.
  const inlineScripts = [
    ...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi),
  ]
  for (const [full, body] of inlineScripts) {
    if (/type=["']application\/ld\+json["']/i.test(full)) continue
    if (body.trim().length === 0) continue
    warnings.push(`${rel}: unexpected inline <script>: ${full.slice(0, 100)}…`)
  }
}

if (warnings.length > 0) {
  console.warn(`\n${warnings.length} warnings:`)
  for (const w of warnings) console.warn(`  ! ${w}`)
}

if (errors.length > 0) {
  console.error(`\n${errors.length} validation errors:`)
  for (const e of errors) console.error(`  ✗ ${e}`)
  process.exit(1)
}

console.log(`\n✓ All ${ssgFiles.length} prerendered HTML files pass validation gates`)
// Intentional: avoid `process.exit(0)` so the script integrates with build
// pipelines that interpret a hung handle as success.
